spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://eyw6324oty5fsovx.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/fviooy06yi2yn29z
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: 'true'
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: create
  cache:
    type: redis
    redis:
      host: redis-13949.c11.us-east-1-2.ec2.cloud.redislabs.com
      port: 13949
      password: ${REDIS_PASSWORD}
    mail:
      host: smtp.mailtrap.io
      port: 2525
      username: c3d3ffffd0f574
      password: 2b812338d8b222
      properties:
        mail:
          transport:
            protocol: smtp
          debug: true
          smtp:
            auth: true
            starttls:
              enable: true
jwt:
  secret: secret