name: CI

on:
  push:
    branches:
      - '*'

jobs:
  in-docker_test:
    name: Automated tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Cache of deps
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/build.gradle.kts') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Execute tests
        run: ./gradlew test